### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by flaxues** [LazerSoft1/MysteryCrates#1]
16:55:59 [CRITICAL] "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'MysteryCrates v1': Class crates\TextFormat not found on crates\Main
16:55:59 [CRITICAL] ClassNotFoundException: "Class crates\TextFormat not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by RandomAltThing** [comment]
I forgot to import the
<code>pocketmine\utils\TextFormat</code> class

**Comment by xHFx** [comment]
Dummy ^ haha

**Comment by SavionLegendZzz** [comment]
.-.

**Comment by RandomAltThing** [comment]
Lol
