### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by flaxues** [LazerSoft1/MysteryCrates#2]
So i installed the plugin and if i know click on the chest with item it's just saying: 

MysteryCrates>> Matthww opened a crate!

and i get nothing it's just broadcast that message

**Comment by xHFx** [comment]
Any errors or crashes? Check the console please

**Comment by RandomAltThing** [comment]
That hasn't been implemented yet

**Comment by SavionLegendZzz** [comment]
https://github.com/SavionLegendZzz/CrateKeys/tree/master

**Comment by RandomAltThing** [comment]
Maybe PR that here? :)

**Comment by SavionLegendZzz** [comment]
pr?

**Comment by xHFx** [comment]
pr?

**Comment by RandomAltThing** [comment]
Pull request duh

**Comment by SavionLegendZzz** [comment]
oh idc

**Comment by xHFx** [comment]
Bye
